"""updated client_drivers table

Revision ID: 4580928a2a03
Revises: b455b1dd5ce1
Create Date: 2024-03-21 13:25:13.705217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4580928a2a03'
down_revision = 'b455b1dd5ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_drivers', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_drivers', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
