"""updated the two tables

Revision ID: 23753830a2e2
Revises: e42da02b7c67
Create Date: 2024-03-21 12:11:36.401546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23753830a2e2'
down_revision = 'e42da02b7c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
