"""Created a join table(client_drivers) and relationship between the tables

Revision ID: b455b1dd5ce1
Revises: 23753830a2e2
Create Date: 2024-03-21 13:18:26.153231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b455b1dd5ce1'
down_revision = '23753830a2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_drivers',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True, extend_existing=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('start_location', sa.String(), nullable=False),
    sa.Column('end_location', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('client_drivers')
    # ### end Alembic commands ###
