"""Added a property decorator to phone in clients table

Revision ID: fde69c9f08c0
Revises: a69e345841b6
Create Date: 2024-03-21 10:29:29.733523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde69c9f08c0'
down_revision = 'a69e345841b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.INTEGER(), nullable=True))
    op.drop_column('clients', 'location')
    # ### end Alembic commands ###
